### PR TITLE
Updated utils.jl to include checkPermissions() and fix checkFolder()

### LINKED ISSUE #34: Add in cases for folders or files not found in loader.jl for prepareDSP() and prepareHit()
At present, if a folder or file does not exist, there is no error message or anything to let you know; this causes kernels to die unexpectedly in IJulia, so adding in an if-else case here would be useful. I found this in prepareDSP(): 

https://github.com/legend-exp/legend-julia-dsp-scripts/blob/d6329033b982b793c85e4f9ac140692e07cebce8/utils/loader.jl#L290-L294

and in prepareHit():

https://github.com/legend-exp/legend-julia-dsp-scripts/blob/d6329033b982b793c85e4f9ac140692e07cebce8/utils/loader.jl#L373-L380

### PR DESCRIPTION
**Pull request by dcschaper**
Calls to checkFolder() were failing before under the edge case that the folder specified did not exist, the user wanted to create it, but did NOT have write permission in the target directory. Added in a checkPermissions() function to utils.jl and then included this function in the checkFolder() function.

### CODE REVIEW

File: utils/utils.jl [hunk 1]
```diff
@@ -1,13 +1,79 @@
...
+"Checks if a folder exists; if it does, do nothing. If folder does not exist, attempts to create directory."
 function checkFolder(folder::PosixPath, create::Bool=false)
-    if !exists(folder)
-        if create
-            println("Create folder $folder")
-            mkpath(folder)
+    if !exists(folder) #if directory 'folder' does not exist:
+        if create #if create is set to true (it is false by default)
+            if (checkPermissions(splitdir(folder)[1], "w")==true) # checking parent directory to see if it is writable before attempting to create new folder.
+                println("Create folder $folder")
```
Comment (oschulz) [inline utils/utils.jl]: Use

```julia
@info "Create folder $folder"
```

instead of `println` (except where a program produces it's actual output on the console). If it's output only relevant for debugging, use `@debug ...` instead of `@info ..`.

File: utils/utils.jl [hunk 2]
```diff
@@ -1,13 +1,79 @@
...
+false
+
+julia> (x==false)
+true
+julia> !(x==false)
+false
+```
+"""
+function checkPermissions(path, mode::String) # written like this to allow 'path' to be either a String or PosixPath
+    # Inside of this function, 'path' needs to be a string here because we are using ccall. First check if the input 'path' is of type PosixPath
```
Comment (oschulz) [inline utils/utils.jl:34]: Try using `uperm(filename)` instead of `ccall` - would probably be better cross-platform.

**Review by oschulz — CHANGES_REQUESTED** [review]

File: utils/utils.jl (hunk 2 above)
Comment (dcschaper) [reply utils/utils.jl:34]: I agree with you that `ccall` might not be great cross-platform, but I don't think `uperm()` is the correct function since it returns the permissions of the OWNER of the file (see docs at https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.uperm) and not the specific user who is querying the permissions. The other options are `gperm` and `operm` for group and not-the-owner-and-not-in-the-group cases, but I thought that, for example, using `operm` could possibly return an edge case if the situation where the querying user was NOT the owner of a file/directory, but WAS in a group with control over it. `ccall` was at least returning the expected values. I agree, we should find a more elegant solution in the future.

Comment (oschulz) [reply utils/utils.jl:34]: You're right, we can't use `uperm` here, let's stick with your solution for now.
